---
title: 'Final Exam Information'
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float: true 
   theme: flatly
---

<br/>

# STA130 Final Exam Frequently Asked Questions

## When and where is the exam?

See the University of Toronto's Faculty of Arts and Science [April 2018 Examination Timetable](http://www.artsci.utoronto.ca/current/exams/apr18).

## What are the rules for writing an exam at UofT? 

See the University of Toronto's [Exam Rule Reminder](http://www.artsci.utoronto.ca/current/exams/reminder)

## What content will be covered on the final exam? 

The final exam will include **all** the material covered in the course.  The material covered in the course can be found on the [course content page](course_content.html).

## What should I study?

The exam will cover all the material *before* and *after* the midterm test.  So, study:

- [lecture notes](course_content.html), 

- [weekly practice problems](course_content.html), 

- [midterm tests](term_test_2018.html), 

- [mideterm test review](http://52.235.36.76:3838/STA130MidtermReview/), and 

- final exam [sample questions](exam_review_student.pdf).  

## How many questions?

There are 23 multiple choice questions, and one writing question.  

## How much is each question worth?

The value of each question is given on the [April 2018 exam cover page](exam_coverpage.pdf).

## Should I study previous STA130 final exams?

No.  The course content has substantially changed from previous years.

## Are there any sample questions available?

Yes.  Professors Taback and Gibbs have created sample questions available [here](exam_review_student.pdf).  Answers to these questions will be posted later.

## Will there be office hours before the exam?

Yes.  The schedule is below.

All office hours will be in SS623B.

| Date   | Day       | Hours   | TA               |
|--------|-----------|---------|------------------|
| 09-Apr | Monday    | 11-2pm  | Sheng            |
|        |           | 1pm-3pm | Yao              |
| 10-Apr | Tuesday   | 10-12pm | Yao              |
|        |           | 12-2pm  | Yao              |
| 11-Apr | Wednesday | 10-12pm | Saneea           |
|        |           | 12-2pm  | Saneea           |
|        |           | 2-4pm   | Lee              |
|        |           | 2-5pm   | Zahra            |
| 12-Apr | Thursday  | 10-12pm | Mathieu, Mingyan |
|        |           | 12-2pm  | Lee, Andy        |
|        |           | 2-4pm   | Lee, Andy        |
|        |           | 4-5pm   | Yang             |
| 13-Apr | Friday    | 10-11am | Bo               |
|        |           | 11-12pm | Bo, Mingyan      |
|        |           | 12-1pm  | Bo, Mingyan      |
|        |           | 1-2pm   | Yasha, Andy      |
|        |           | 2-3pm   | Yasha, Andy      |
|        |           | 3-4pm   | Yasha, Andy      |
|        |           | 4-5pm   | Yang             |
| 16-Apr | Monday    |         |                  |
|        |           | 11-12pm | Yue(Carrie), Bo  |
|        |           | 12-1pm  | Yue(Carrie), Bo  |
|        |           | 1-2pm   | Yue(Carrie), Bo  |
|        |           | 2-3pm   | Jiayue, Yunjing  |
|        |           | 3-4pm   | Jiayue, Yunjing  |
|        |           | 4-5pm   | Yunjing          |