---
title: "R Resources for STA130H1S"
date:
output: 
  html_document:
    theme: flatly
---

There are lots of free resources available for learning R.  This page contains some excellent resources, but we certainly can't list all the excellent resources available.

# Running R 

<a href= "https://www.r-project.org"><i class="fab fa-r-project fa-1x"></i></a> is a software environment for statistical computing and graphics that can be freely downloaded at [CRAN](https://cran.r-project.org).

[RStudio](https://www.rstudio.com) is a popular integrated development environment for <i class="fab fa-r-project fa-1x"></i> that we will be using throughout the course.

There are two ways that students can run R using RStudio:

1. Create an account on [RStudio Cloud](https://rstudio.cloud).

2. Install RStudio on your computer.  A desktop version is available to [download](https://www.rstudio.com/products/rstudio/#Desktop) on to your personal computer for free. 


# Getting Started with R

- If you have never programmed before then [Hands-On Programming with R, by Garrett Grolemund](https://d1b10bmlvqabco.cloudfront.net/attach/ighbo26t3ua52t/igp9099yy4v10/igz7vp4w5su9/OReilly_HandsOn_Programming_with_R_2014.pdf) is a great place to start.
- [R for Data Science, by Hadley Wickham and Garrett Grolemund](http://r4ds.had.co.nz) is a wonderful resource. 
- [Datacamp](https://www.datacamp.com) offers a free online [Introduction to R](https://www.datacamp.com/courses/free-introduction-to-r).


# R Style Guide

> Good coding style is like correct punctuation: you can manage without it, butitsuremakesthingseasiertoread. Just as with punctuation, while there are many code styles to choose from, some are more reader-friendly than others. _Hadley Wickham, [Tidyverse Style Guide](http://style.tidyverse.org/index.html)._

When you write code, especially when it will be read by other people (e.g., your TA), refer to the [Tidyverse Style Guide](http://style.tidyverse.org/index.html) for best practices.  

# R Markdown 

[R Markdown](http://rmarkdown.rstudio.com) documents can be used to create documents that weave together code and text.  

An R Markdown Cheat Sheet downloaded from [RStudio](https://www.rstudio.com/resources/cheatsheets/) is available [here](rmarkdown-2.0.pdf).

A guide to producing R Markdown documents for class assignments is available [here](Rmarkdownforclassreports.html).  This guide also includes a short introduction to $\LaTeX$ for including math in R Markdown.

# Getting Help with R

Students can always ask a member of the teaching staff for help during office hours, tutorial, or on the class [discussion forum](https://piazza.com/utoronto.ca/winter2018/sta130h1/home).

[stackoverflow](https://stackoverflow.com) is a popular forum for posting and answering questions related to programming.  Questions tagged R can be found [here](https://stackoverflow.com/questions/tagged/r) and questions tagged RStudio can be found [here](https://stackoverflow.com/questions/tagged/rstudio).

R Markdown source for this page  <a href="https://raw.githubusercontent.com/ntaback/UofT_STA130/master/R_resources.Rmd">
<i class="fa fa-github fa-2x" aria-hidden="true"></i>
</a>


