---
title: "STA130 Course Content"
date: 'Fall 2018'
output: 
  html_document:
   toc: true
   toc_depth: 2
   toc_float: true 
   theme: flatly
   css: ../custom.css
---

```{r, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

This page contains course material such as class slides, practice problems, and tutorial assignments.


# Week 0

## September 7 Tutorial

There are no tutorials on September 7.  Instead of attending tutorial we suggest that you spend some time getting acquainted with the basics of [R](https://www.r-project.org).  We will be using R throughout the course.

The first classes are on September 10.  Before you come to class do the following:

0. Read through the course syllabus.

1. Read the [R resources section](../R_resources.html) of the course webpage.

2. Sign up for the [Piazza discussion forum](https://piazza.com/utoronto.ca/fall2018/sta130h1).

3. Get introduced to R.  Two ways to get you started are:

(i) Sign up for [R Studio Cloud](https://rstudio.cloud)

(ii) Complete the tutorial on [R programming basics](https://rstudio.cloud/learn/primers/1.2).  If you would like a deeper introductory R programming tutorial then complete [Datacamp's](https://www.datacamp.com) free online [Introduction to R](https://www.datacamp.com/courses/free-introduction-to-r)

(iii)  Read chapters 1, 2, and 3 of [Hands-On Programming with R, by Garrett Grolemund](https://d1b10bmlvqabco.cloudfront.net/attach/ighbo26t3ua52t/igp9099yy4v10/igz7vp4w5su9/OReilly_HandsOn_Programming_with_R_2014.pdf).  

You can do both (ii) and (iii), but a lot of the same content is covered. If you decide to only complete the readings then make sure to type the commands into the console window in RStudio.    

# Week 1

## September 10 Class

### Topics

- Course overview.
- Introduction to data vizualization using the `ggplot2` library in R.
- Histrograms, bar graphs, scatter plots, faceting.
- Distribution of quantitative and numerical variables.

### Slides

Prof. Taback's class slides - Mon 10:00 (L0101): [html](week1/sta130_sept10_nt.html), [pdf](week1/sta130_sept10_nt.pdf).

Prof. Moon's class slides - Mon 14:00 (L0201): [pdf](week1/week1_nm_posted.pdf), 
[pdf - anotated](week1/Week1_nm_in-class_annotated.pdf)


### References

1. [Data Visualization Basics](https://rstudio.cloud/learn/primers/1.1)

2. Grolemund, G. and Wickham, H. R for Data Science. [Chapter 3](http://r4ds.had.co.nz/data-visualisation.html).


## September 14 Tutorial

<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>  Read [this](week1/tutorial/howtoanswertutq_sept14.html) before answering practice problems using RStudio.

<span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> [Practice problems](week1/tutorial/Week1PracticeProblems-Fall2018-student.html)

<span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> [Practice problems - Sample Solutions](week1/tutorial/solutions/Week1PracticeProblems-Fall2018-solutions.html)



# Week 2

## September 17 Class

### Topics

- Introduction to programming with R
    + RStudio user interface
    + R Objects
    + R Functions
    + R Scripts
    + R Packages
    + R Lists
    + R Notation
    + R Missing Data

- Numerical descriptions of the distribution of quantitative variable

### Slides

Prof. Taback's class slides - Mon 10:00 (L0101): [html](week2/sta130_sept17_nt.html), [pdf](week2/sta130_sept17_nt2.pdf).

Prof. Moon's class slides - Mon 14:00 (L0201): [pdf](https://www.dropbox.com/s/9zt6s6wtqda85fd/week2slides_nm.pdf?dl=0),
[pdf - anotated](https://www.dropbox.com/s/8y6e7bzsu665muq/week2slides_nm_annotated.pdf?dl=0)

Flu data used in class (csv format): [Provincial Flu data](week2/fludat_prov.csv), [Provincial Population Size](week2/popdat.csv).

### References

1. [Hands on Programming With R. G. Grolemund - Chapters 1-5](https://d1b10bmlvqabco.cloudfront.net/attach/ighbo26t3ua52t/igp9099yy4v10/igz7vp4w5su9/OReilly_HandsOn_Programming_with_R_2014.pdf)

2. [Introductory Statistics with Randomization and Simulation. Diez, D.M., Barr, C.D., and Çetinkaya-Runde, M. . Section 1.6](https://www.openintro.org/download.php?file=isrs1_tablet&referrer=/stat/textbook.php)

## September 21 Tutorial

<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>  Read [this](week2/tutorial/howtoanswertutq_sept21.html) before answering practice problems using RStudio.

<span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> [Practice problems](week2/tutorial/Week2PracticeProblems-Fall2018_student.html)

<span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> [Practice problems - Sample Solutions](week2/tutorial/solutions/Week2PracticeProblems-Fall2018_soltns.html)

# Week 3

## September 24 Class

### Topics

- Statistical data
- Tidy data
- Data wrangling
- Boxplots


### Slides 

Prof. Taback's class slides - Mon 10:00 (L0101): 

<span class="glyphicon glyphicon-scissors" aria-hidden="true"></span> The slides on joining (merging) data frames and the Trump tweets example have been removed.  You are not responsible for these topics or undertsanding this example this week.  This topic will be covered on Oct.1

- [html](week3/sta130_sept24_nt_revised.html)

- [pdf](week3/sta130_sept24_nt_revised.pdf) 

- [pdf -annotated](week3/sta130_sept24_nt_annotated.pdf)

Prof. Moon's class slides - Mon 14:00 (L0201): 

- [pdf](https://www.dropbox.com/s/ghmu18htdkzxc5c/week3slides_nm.pdf?dl=0)

- [pdf - annotated](week3/week3slides_nm_annotated.pdf)

### References

1. Grolemund, G. and Wickham, H. R for Data Science. [Chapter 5](http://r4ds.had.co.nz/transform.html).

2. [Introductory Statistics with Randomization and Simulation. Diez, D.M., Barr, C.D., and Çetinkaya-Runde, M. . Section 1.7](https://www.openintro.org/download.php?file=isrs1_tablet&referrer=/stat/textbook.php)

3. (**Optional paid course**) Data Camp Online Course. [Data Manipulation in R with dplyr](https://www.datacamp.com/courses/dplyr-data-manipulation-r-tutorial)

#### Articles of Interest

[For Big-Data Scientists, ‘Janitor Work’ Is Key Hurdle to Insights - NYT](https://www.nytimes.com/2014/08/18/technology/for-big-data-scientists-hurdle-to-insights-is-janitor-work.html) <i class="fa fa-external-link" aria-hidden="true"></i>

[The Economic Guide To Picking A College Major - FiveThirtyEight](https://fivethirtyeight.com/features/the-economic-guide-to-picking-a-college-major/) <i class="fa fa-external-link" aria-hidden="true"></i>

[dplyr cheat sheet #1](data-transformation.pdf), [dplyr cheat sheet #2](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)

## September 28 Tutorial

<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>  Read [this](week3/tutorial/howtoanswertutq_sept28.html) before answering practice problems using RStudio.

<span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> [Practice problems](week3/tutorial/Week3PracticeProblems_student.html) 

<span class="glyphicon glyphicon-scissors" aria-hidden="true"></span> (**NB: One question has been removed from the original post on Sept 23**)

<span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> [Practice problems - Sample Solutions](week3/tutorial/Week3PracticeProblems_solutions.html)

# Week 4

## October 1 Class

### Topics

- Introduction to statistical inference
- `for` loops
- Simulation
- Inference for a single proportion
- Hypothesis testing

### Slides 

Prof. Taback's class slides - Mon 10:00 (L0101): 

- [html](week4/sta130_oct1_week4_ver1.html)

- [pdf](week4/sta130_oct1_week4_ver1.pdf) 

- [pdf -annotated](week4/sta130_oct1_week4_ver1_annotated.pdf)

Prof. Moon's class slides - Mon 14:00 (L0201):

- [pdf](https://www.dropbox.com/s/dje949awvlvzd6g/week4slides_posted_nm.pdf?dl=0)

- [pdf - annotated](week4/week4slides_posted_nm_annotated.pdf)


### References

Sections 2.3.1, 2.3.2, 2.3.7 and 2.4 of [*Introductory Statistics with Randomization and Simulation* from OpenIntro](https://www.openintro.org/stat/textbook.php?stat_book=isrs)  

## October 5 Tutorial

<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>  Read [this](week4/tutorial/howtoanswertutq_oct5.html) before answering practice problems using RStudio.


<span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> [Practice problems](week4/tutorial/Week4PracticeProblems_questions_v3.html) 

<span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> [Practice problems - Sample Solutions](week4/tutorial/Week4PracticeProblems_solutions_v3.html)


# Week 5

## October 8 Class - No Class due to Thanksgiving, but there is a tutorial on Friday, October 12

The tutorial will cover joining data frames.  A short lesson on joining data frames is given [here](week5/joiningdataframes.html).  It is strongly recommended that you study this before attempting the tutorial questions.

### Topics

- Joining two data frames.

## October 12 Tutorial

<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>  Read [this](week5/howtoanswertutq_oct12.html) before answering practice problems using RStudio.

<span class="glyphicon glyphicon-hand-right" aria-hidden="true"> </span> [Practice problems](week5/Week5PracticeProblems_questions.html) 

<span class="glyphicon glyphicon-hand-right" aria-hidden="true"> </span> [Practice problems - solutions](week5/solutions/Week5PracticeProblems_solutions.html) 



### References

1. Grolemund, G. and Wickham, H. R for Data Science. [Chapter 13.1 - 13.4](http://r4ds.had.co.nz/relational-data.html).

2. dplyr reference for [Join two tbls together](https://dplyr.tidyverse.org/reference/join.html)


# Week 6

## October 15 Class

### Topics

- Comapring two proportions
- Comapring two means 
- Type I and Type II Errors
- Interpretation of P-values

### Slides 

Prof. Taback's class slides - Mon 10:00 (L0101): 

- [html](week6/sta130_oct15_week6.html)

- [pdf](week6/sta130_oct15_week6.pdf) 

- [pdf -annotated](week6/sta130_oct15_week6-annotated.pdf)

Prof. Moon's class slides - Mon 14:00 (L0201)

- [pdf](week6/slides_oct15_nm_posted.pdf)

- [pdf -annotated](week6/slides_oct15_nm_annotated.pdf)

### References

Recommended reading:  
Sections 2.1, 2.2, 2.3 (excluding 2.3.4) of [*Introductory Statistics with Randomization and Simulation* from OpenIntro](https://www.openintro.org/stat/textbook.php?stat_book=isrs)  
(a free open-source textbook)

## October 19 Tutorial

<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>  Read [this](week6/Tutorial/howtoanswertutq_oct19.html) before answering practice problems using RStudio.

<span class="glyphicon glyphicon-hand-right" aria-hidden="true"> </span> [Practice problems](week6/Tutorial/Week6PracticeProblems_student.html) 

<span class="glyphicon glyphicon-hand-right" aria-hidden="true"> </span> [Practice problems - solutions](week6/Tutorial/Week6PracticeProblems_solutions.html) 


# Week 7

## October 22 Class

### Topics

- Review class

### Slides

Prof. Taback's class slides - Mon 10:00 (L0101):

- [html](week7/sta130_week7_test_review.html)

- [pdf](week7/sta130_week7_test_review.pdf)

Prof. Moon's class slides - Mon 14:00 (L0201):

- [pdf](https://www.dropbox.com/s/wkbbwyi0viz9hnf/slides_oct22_review_nm.pdf?dl=0)

## October 26 Tutorial

Midterm test during tutorial.  See [term test information](term_test_Fall2018.html). 

<div class=second>

# Week 8

## October 29 Class

### Slides and References

## October 29 Tutorial


# Fall Reading Week 

- No classes or tutorials


# Week 9

## November 12 Class

### Slides and References

## November 16 Tutorial


# Week 10

## November 19 Class

### Slides and References

## November 23 Tutorial

# Week 11

## November 26 Class

### Slides and References

## November 30 Tutorial


# Week 12

## December 3 Class

### Slides and References

## STA130 Poster Fair - Thursday, December 6

</div>

